### ISSUE TITLE
Listing of CATs based on transaction volume with time scale like 24hr,1w,1m,1y

### ISSUE THREAD

**Issue by spacescan-io** [spacescan-io/web#1]
**List the CAT in CAT tracker page based on transactions volume.**

- The default listing should be 24hr
- There should be an option to toggle for 1w, 1m and all time

**Comment by JagRudh** [comment]
This is implemented into spacescan.io.

Refer : https://www.spacescan.io/xch/cat1/topTokens

![Screenshot from 2022-02-22 22-15-28](https://user-images.githubusercontent.com/100055538/155256197-6d447da5-809d-4432-9ecd-2f20a803559c.png)
