### ISSUE TITLE
Charts not working for Testnet 10

### ISSUE THREAD

**Issue by spacescan-io** [spacescan-io/web#12]
There is not data for 24hrs so charts are not showing any charts for 24hr for below charts.
all Mempool
all Cats

![image](https://user-images.githubusercontent.com/96506753/155894762-76251e78-68c0-4225-8c16-bbb1bdc4ee76.png)

**Comment by ajayZorro** [comment]
This is working fine now. Closing with the screenshot attached for this 
![image](https://user-images.githubusercontent.com/100055843/158077735-faaf09ee-4c70-4972-bfb3-400315a9f170.png)
