### ISSUE TITLE
Bug - New address showing only loading icon

### ISSUE THREAD

**Issue by spacescan-io** [spacescan-io/web#4]
When new address with no coin searched in spacescan.io then the address block is showing only loading icon.
Need to show user friendly message like no balance found.
Sample account - https://www.spacescan.io/xch/address/xch1sdth2kv8l5t20qdy73z6qu9vety77gsj7nrc2m4njc4f57yups9s9995qs
![image](https://user-images.githubusercontent.com/96506753/154828183-06b31061-e4bf-48b5-a324-675ebc2d5dd7.png)

**Comment by JagRudh** [comment]
Team this is fixed.
