### ISSUE TITLE
Optimization - Update price api in spacescan from api to api2

### ISSUE THREAD

**Issue by natsabari** [spacescan-io/web#41]
The price api is avaialble from api2 with higher caching, so we can replace the price api in spacescan.io with new api2.
old : https://api.spacescan.io/1/xch/price/24hr
new: https://api2.spacescan.io/1/xch/price/24hr

**Comment by shamhiruthik** [comment]
The price API is updated to API2 and pushed to the main,Ready to Deploy!

**Comment by steppsr** [comment]
What other endpoints are available for price? I was hoping I could target a specific date.
