### ISSUE TITLE
Refactor Top Breadcrumps

### ISSUE THREAD

**Issue by ajayZorro** [spacescan-io/web#43]
The top breadcrumbs need to be refactored in the following ways. 

First Navigation section
- Home button remains the same 
Second Navigation Section
- Instead of tokens, replace the navbar with 'Blockchain'
- Inside this blockchain, we need a horizontal dropdown where we will have 'Blocks & Coins' section where we will have view coins, view blocks, price chart, XCH per TiB chart. 
- Inside this blockchain, the next column will be mempool which will have all the links that are now present under the mempool chart sections
- Inside this blockchain, the next column will be the netspace, which will have all the links that are now present under the Netspace chart section. 
Third Navigation Section
- Instead of charts, replace the navbar with CATs
- Inside the CATs, we have a vertical dropdown, where we will have CAT1 catalog, CAT1 token tracker, CAT1 Transfer, Number of Txns, Txns amount and Add token links

**Comment by shamhiruthik** [comment]
Pushed the codes and synced the main branch. I have created a pull request but it's automatically synced with the main branch. But no worries all are working properly you just pull the synced branch and check it out. Both the Desktop view and Mobile View are updated.

**Comment by natsabari** [comment]
This change is deployed in last iteration, we can close this issue.

**Comment by shamhiruthik** [comment]
Completed and Deployed
