### ISSUE TITLE
Pool Contract Address

### ISSUE THREAD

**Issue by william-gr** [spacescan-io/web#5]
![image](https://user-images.githubusercontent.com/56250/155145386-9051123d-518a-4a4c-85be-492a23b1396c.png)

https://www.spacescan.io/xch/block/height/1598032

Hello! I was checking the block farmed by one of my pool members. In the block info there is "Pool Address", which can be a bit confusing. Would it make sense and be possible to rename it to "Pool Contract Address" which is what it really is?

Additionally to that, is it possible to the the pool wallet address too?

Thanks!

**Comment by spacescan-io** [comment]
Hi William,
 The request here is to rename the  "Pool Address" to "Pool Contract Address" right?
 This we can do it quickly and may be in future we can just show the pool name like "Openchia.io"
 
 what you mean by pool wallet address here? could you explain more on this.
 **"Additionally to that, is it possible to the the pool wallet address too?"**
 
 Thank you

**Comment by william-gr** [comment]
The Pool Contract Address is per Plot NFT, what I mean is that it would be nice if we could get what is the wallet address the plot NFT is currently assigned to (singleton) which is where is the 7/8 of the reward going to (pool wallet address).

Did I make myself more clear?

Thanks

**Comment by spacescan-io** [comment]
Yes, let me check on that also. I was thinking would that be good to show pool name there instead of address. Like openchia.io in the pool address place, I think that would be much more readable for users and we can even add link to pool website from here!

**Comment by JagRudh** [comment]
@william-gr This is implemented.

![image](https://user-images.githubusercontent.com/100055538/155457039-e4a8e5fb-9b2c-4905-938e-ffbe6ff090bd.png)

**Comment by william-gr** [comment]
Thank you!
