### ISSUE TITLE
Social links missing https in CAT page

### ISSUE THREAD

**Issue by spacescan-io** [spacescan-io/web#6]
The social links doesn't have https and leading to nowhere !

https://www.spacescan.io/xch/cat1/a56b38245583e2014e24e01dfcc2d6a5a6b19c15110093eca14dfeda817aa2da

**Comment by spacescan-io** [comment]
It's added by the issuer in cat form so it's not an issue with display. We can close it. 

We can remove other icons which is not having social links.

**Comment by JagRudh** [comment]
This is fixed
