### ISSUE TITLE
[BUG] - NFTs not loaded properly

### ISSUE THREAD

**Issue by forReason** [spacescan-io/web#63]
spacescan.io wont load my nfts.
The picture is just a green striked circle (seen that at plenty other NFT's as well)

The Metadasa says its not compliant but the syntax was prooven and the json checked vs the official schema.
Other plattforms and the client show the nft properly and the metadata is loaded fine:

https://www.spacescan.io/xch/nft/nft19ka8j4qe4dxgexwyued234uz2ne30mnjgp0hm0kfrktntqxemmzspr4npp

![image](https://user-images.githubusercontent.com/12736950/199973314-8c652aa2-d931-4451-a6e4-c45af802bcfa.png)

**Comment by natsabari** [comment]
The issue is fixed and working on better systems.
Thank you informing,

**Comment by natsabari** [comment]
![image](https://user-images.githubusercontent.com/2860620/200176973-5881f86f-fe6a-4799-a685-c45e428e38db.png)
